# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180323_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='vp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
