# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180323_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='vp',
            new_name='pv',
        ),
    ]
