# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_login_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_data',
        ),
    ]
