# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_login_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': (('read_title', 'Can read title'),)},
        ),
    ]
